swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /users:
    get:
      operationId: "user.read"
      tags:
        - "User"
      summary: "The people data structure supported by the server application"
      description: "Read the list of people"
      responses:
        200:
          description: "Successful read people list operation"
          schema:
            type: "array"
            items:
              properties:
                id:
                  type: "string"
                nom:
                  type: "string"
                prenom:
                  type: "string"
                mdp:
                  type: "string"
                ddn:
                  type: "string"
                mail:
                  type: "string"
                adr_livraison:
                  type: "string"
                code_pos:
                  type: "string"
                ville:
                  type: "string"
                pays:
                  type: "string"
                tel:
                  type: "string"
                num_carte:
                  type: "string"
                username:
                  type : "string"

#  /adduser:
#    post:
#      operationId: "user.insert"
#      tags:
#        - "Insert"
#      summary: "The people data structure supported by the server application"
#      description: "Insert people"
#      parameters:
#        - in: formData
#          name: nom
#          type : string
#          description: un nom
#        - in: formData
#          name: prenom
#          type : string
#          description: un prenom
#        - in: formData
#          name: mdp
#          type: string
#          description: mot de passe
#        - in: formData
#          name: ddn
#          type: string
#          description: date de naissance
#        - in: formData
#          name: mail
#          type: string
#          description: mail
#        - in: formData
#          name: adr_liv
#          type: string
#          description: adresse de livraison
#        - in: formData
#          name: code
#          type: integer
#          description: code postal
#        - in: formData
#          name: ville
#          type: string
#          description: une ville
#        - in: formData
#          name: pays
#          type: string
#          description: pays
#        - in: formData
#          name: tel
#          type: integer
#          description: numero de telephone
#        - in: formData
#          name: carte
#          type: integer
#          description: carte de credit
#        - in: formData
#          name: username
#          type: string
#          description: pseudo
#      responses:
#        200:
#          description: OK

  /user/{id}:
    get:
      operationId: "user.getid"
      parameters:
        - in: path
          name: id
          type: string
          required: true
          description: Numeric ID of the user to get
      responses:
        200:
          description: OK
